CREATE TABLE "DEV"."FOOD"
   ("FOOD_ID" NUMBER,
	"FOOD_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"FOOD_TYPE" NUMBER,
	"ALT_FOODNAME" VARCHAR2(100),
	"IS_ORGANIC" NUMBER(1,0) NOT NULL ENABLE,
	"STORE_ID" NUMBER,
	 PRIMARY KEY ("FOOD_ID")
      USING INDEX  ENABLE,
	 UNIQUE ("FOOD_NAME")
      USING INDEX  ENABLE,
	 FOREIGN KEY ("FOOD_TYPE")
	  REFERENCES "DEV"."FOOD_TYPE" ("TYPE_ID") ENABLE,
	 FOREIGN KEY ("STORE_ID")
	  REFERENCES "DEV"."GROCERY_STORE" ("STORE_ID") ENABLE
   );
   
   CREATE INDEX "DEV"."I_STOREID$GROCERY_STORE" ON "DEV"."FOOD" ("STORE_ID");
   CREATE INDEX "DEV"."I_FOODTYPE$FOOD" ON "DEV"."FOOD" ("FOOD_TYPE");
   
   COMMENT ON COLUMN "DEV"."FOOD"."FOOD_ID" IS 'Food identifier';
   COMMENT ON COLUMN "DEV"."FOOD"."FOOD_NAME" IS 'Food name';
   COMMENT ON COLUMN "DEV"."FOOD"."FOOD_TYPE" IS 'Type of food';
   COMMENT ON COLUMN "DEV"."FOOD"."ALT_FOODNAME" IS 'Alternative name';
   COMMENT ON COLUMN "DEV"."FOOD"."IS_ORGANIC" IS '0 - other 1 - organic';
   COMMENT ON COLUMN "DEV"."FOOD"."STORE_ID" IS 'Grocery store identifier';