CREATE TABLE "DEV"."FOOD_LOG"
   ("FL_ID" NUMBER,
	"ML_ID" NUMBER NOT NULL ENABLE,
	"RCP_ID" NUMBER NOT NULL ENABLE,
	"MEAL_ID" NUMBER NOT NULL ENABLE,
	"FOOD_ID" NUMBER NOT NULL ENABLE,
	"AMOUNT" NUMBER NOT NULL ENABLE,
	"UNIT_ID" NUMBER NOT NULL ENABLE,
	 PRIMARY KEY ("FL_ID")
      USING INDEX  ENABLE,
	 FOREIGN KEY ("ML_ID")
	  REFERENCES "DEV"."MEAL_LOG" ("ML_ID") ENABLE,
	 FOREIGN KEY ("RCP_ID")
	  REFERENCES "DEV"."RECIPE" ("RCP_ID") ENABLE,
	 FOREIGN KEY ("MEAL_ID")
	  REFERENCES "DEV"."MEAL" ("MEAL_ID") ENABLE,
	 FOREIGN KEY ("FOOD_ID")
	  REFERENCES "DEV"."FOOD" ("FOOD_ID") ENABLE,
	 FOREIGN KEY ("UNIT_ID")
	  REFERENCES "DEV"."UNIT" ("UNIT_ID") ENABLE
   );
   
   CREATE INDEX "DEV"."I_MEALID$FOOD_LOG" ON "DEV"."FOOD_LOG" ("ML_ID");
   
   COMMENT ON COLUMN "DEV"."FOOD_LOG"."FL_ID" IS 'Food log identifier';
   COMMENT ON COLUMN "DEV"."FOOD_LOG"."ML_ID" IS 'Meal log identifier';
   COMMENT ON COLUMN "DEV"."FOOD_LOG"."RCP_ID" IS 'Recipe identifier';
   COMMENT ON COLUMN "DEV"."FOOD_LOG"."MEAL_ID" IS 'Meal identifier';
   COMMENT ON COLUMN "DEV"."FOOD_LOG"."FOOD_ID" IS 'Food identifier';
   COMMENT ON COLUMN "DEV"."FOOD_LOG"."AMOUNT" IS 'Food amount';
   COMMENT ON COLUMN "DEV"."FOOD_LOG"."UNIT_ID" IS 'Unit identifier';