CREATE TABLE "DEV"."FOOD$UNIT"
   ("FU_ID" NUMBER,
	"FOOD_ID" NUMBER NOT NULL ENABLE,
	"UNIT_ID" NUMBER NOT NULL ENABLE,
	 PRIMARY KEY ("FU_ID")
      USING INDEX  ENABLE,
	 CONSTRAINT "UNIQUE_FOODUNIT" UNIQUE ("FOOD_ID", "UNIT_ID")
      USING INDEX  ENABLE,
	 FOREIGN KEY ("FOOD_ID")
	  REFERENCES "DEV"."FOOD" ("FOOD_ID") ENABLE,
	 FOREIGN KEY ("UNIT_ID")
	  REFERENCES "DEV"."UNIT" ("UNIT_ID") ENABLE
   );
   
   CREATE UNIQUE INDEX "DEV"."UNIQUE_FOODUNIT" ON "DEV"."FOOD$UNIT" ("FOOD_ID", "UNIT_ID");
   
   COMMENT ON COLUMN "DEV"."FOOD$UNIT"."FU_ID" IS 'Id';
   COMMENT ON COLUMN "DEV"."FOOD$UNIT"."FOOD_ID" IS 'Food identifier';
   COMMENT ON COLUMN "DEV"."FOOD$UNIT"."UNIT_ID" IS 'Unit identifier';
