CREATE TABLE "DEV"."GROCERY_STORE"
   ("STORE_ID" NUMBER,
	"STORE_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"STORE_CODE" VARCHAR2(100),
	 PRIMARY KEY ("STORE_ID")
      USING INDEX  ENABLE,
	 CONSTRAINT "UNIQUE_STORE_NAME" UNIQUE ("STORE_NAME")
      USING INDEX  ENABLE
   );
   
   CREATE UNIQUE INDEX "DEV"."UNIQUE_STORE_NAME" ON "DEV"."GROCERY_STORE" ("STORE_NAME");

   COMMENT ON COLUMN "DEV"."GROCERY_STORE"."STORE_ID" IS 'Store identifier';
   COMMENT ON COLUMN "DEV"."GROCERY_STORE"."STORE_NAME" IS 'Store name';
   COMMENT ON COLUMN "DEV"."GROCERY_STORE"."STORE_CODE" IS 'Store code';
