CREATE TABLE "DEV"."MEAL"
   ("MEAL_ID" NUMBER,
	"MEAL_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"ALT_MEALNAME" VARCHAR2(100),
	"IS_HOMEMADE" NUMBER(1,0),
	 PRIMARY KEY ("MEAL_ID")
      USING INDEX  ENABLE,
	 UNIQUE ("MEAL_NAME")
      USING INDEX  ENABLE
    );
    
   COMMENT ON COLUMN "DEV"."MEAL"."MEAL_ID" IS 'Meal identifier';
   COMMENT ON COLUMN "DEV"."MEAL"."MEAL_NAME" IS 'Meal name';
   COMMENT ON COLUMN "DEV"."MEAL"."ALT_MEALNAME" IS 'Alternative name';
   COMMENT ON COLUMN "DEV"."MEAL"."IS_HOMEMADE" IS '0 - other, 1 - homemade';
