CREATE TABLE "DEV"."MEAL_LOG"
   ("ML_ID" NUMBER,
	"ML_DATE" VARCHAR2(1000) NOT NULL ENABLE,
	"ML_TIME" VARCHAR2(1000) NOT NULL ENABLE,
	"ML_DATETIME" DATE NOT NULL ENABLE,
	"MEAL_ID" NUMBER NOT NULL ENABLE,
	"SRVNG_SIZE" NUMBER NOT NULL ENABLE,
	"PERSON_ID" NUMBER NOT NULL ENABLE,
	"COMMENT_" VARCHAR2(2000),
	"WHO_INS" "DEV"."UPD_INFO" ,
	"WHO_UPD" "DEV"."UPD_INFO" ,
	 PRIMARY KEY ("ML_ID")
      USING INDEX  ENABLE,
	 FOREIGN KEY ("MEAL_ID")
	  REFERENCES "DEV"."MEAL" ("MEAL_ID") ENABLE,
	 FOREIGN KEY ("PERSON_ID")
	  REFERENCES "DEV"."PERSON" ("PERS_ID") ENABLE,
	 CONSTRAINT "C_FK_SRVNG_SIZE" FOREIGN KEY ("SRVNG_SIZE")
	  REFERENCES "DEV"."SERVING_SIZE" ("SZ_ID") ENABLE
   );
   
   CREATE INDEX "DEV"."I_MEALID$MEAL_LOG" ON "DEV"."MEAL_LOG" ("MEAL_ID");
   CREATE INDEX "DEV"."I_PERSID$MEAL_LOG" ON "DEV"."MEAL_LOG" ("PERSON_ID");
   
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."ML_ID" IS 'Meal log identifier';
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."ML_DATE" IS 'Log date';
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."ML_TIME" IS 'Log time';
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."ML_DATETIME" IS 'Log datetime';
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."MEAL_ID" IS 'Meal identifier';
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."SRVNG_SIZE" IS 'Serving size';
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."PERSON_ID" IS 'Person identifier';
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."COMMENT_" IS 'Comment';
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."WHO_INS" IS 'Who inserted';
   COMMENT ON COLUMN "DEV"."MEAL_LOG"."WHO_UPD" IS 'Who updated';
