CREATE TABLE "DEV"."MEAL$SERVING_SIZE"
   ("MSZ_ID" NUMBER,
	"MEAL_ID" NUMBER NOT NULL ENABLE,
	"SZ_ID" NUMBER NOT NULL ENABLE,
	 PRIMARY KEY ("MSZ_ID")
      USING INDEX  ENABLE,
	 CONSTRAINT "UNIQUE_MEALSERVINGSIZE" UNIQUE ("MEAL_ID", "SZ_ID")
      USING INDEX  ENABLE,
	 FOREIGN KEY ("MEAL_ID")
	  REFERENCES "DEV"."MEAL" ("MEAL_ID") ENABLE,
	 FOREIGN KEY ("SZ_ID")
	  REFERENCES "DEV"."SERVING_SIZE" ("SZ_ID") ENABLE
   );
   
   CREATE UNIQUE INDEX "DEV"."UNIQUE_MEALSERVINGSIZE" ON "DEV"."MEAL$SERVING_SIZE" ("MEAL_ID", "SZ_ID");
   
   COMMENT ON COLUMN "DEV"."MEAL$SERVING_SIZE"."MSZ_ID" IS 'Identifier';
   COMMENT ON COLUMN "DEV"."MEAL$SERVING_SIZE"."MEAL_ID" IS 'Meal identifier';
   COMMENT ON COLUMN "DEV"."MEAL$SERVING_SIZE"."SZ_ID" IS 'Serving size identifier';
