CREATE TABLE "DEV"."PERSON"
   ("PERS_ID" NUMBER,
	"FIRST_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"MIDDLE_NAME" VARCHAR2(100),
	"DOB" DATE NOT NULL ENABLE,
	"FULL_NAME" VARCHAR2(200),
	 PRIMARY KEY ("PERS_ID")
      USING INDEX  ENABLE
   );
   
   CREATE INDEX "DEV"."I_DOB$PERSON" ON "DEV"."PERSON" ("DOB");
   CREATE INDEX "DEV"."I_FIRSTNAME$PERSON" ON "DEV"."PERSON" ("FIRST_NAME");
   CREATE INDEX "DEV"."I_LASTNAME$PERSON" ON "DEV"."PERSON" ("LAST_NAME");
   
   COMMENT ON COLUMN "DEV"."PERSON"."PERS_ID" IS 'Person identifier';
   COMMENT ON COLUMN "DEV"."PERSON"."FIRST_NAME" IS 'First name';
   COMMENT ON COLUMN "DEV"."PERSON"."LAST_NAME" IS 'Last name';
   COMMENT ON COLUMN "DEV"."PERSON"."MIDDLE_NAME" IS 'Middle name';
   COMMENT ON COLUMN "DEV"."PERSON"."DOB" IS 'Date of birth';
   COMMENT ON COLUMN "DEV"."PERSON"."FULL_NAME" IS 'Full name';
