CREATE TABLE "DEV"."RECIPE"
   ("RCP_ID" NUMBER,
	"MEAL_ID" NUMBER NOT NULL ENABLE,
	"FOOD_ID" NUMBER NOT NULL ENABLE,
	"AMOUNT" NUMBER NOT NULL ENABLE,
	"UNIT_ID" NUMBER NOT NULL ENABLE,
	"BEG_DATE" DATE NOT NULL ENABLE,
	"END_DATE" DATE,
	 PRIMARY KEY ("RCP_ID")
      USING INDEX  ENABLE,
	 CONSTRAINT "UNIQUE_RECIPE_INGRDNTS" UNIQUE ("MEAL_ID", "FOOD_ID")
      USING INDEX  ENABLE,
	 FOREIGN KEY ("MEAL_ID")
	  REFERENCES "DEV"."MEAL" ("MEAL_ID") ENABLE,
	 FOREIGN KEY ("FOOD_ID")
	  REFERENCES "DEV"."FOOD" ("FOOD_ID") ENABLE,
	 FOREIGN KEY ("UNIT_ID")
	  REFERENCES "DEV"."UNIT" ("UNIT_ID") ENABLE
   );
   
   CREATE UNIQUE INDEX "DEV"."UNIQUE_RECIPE_INGRDNTS" ON "DEV"."RECIPE" ("MEAL_ID", "FOOD_ID");
   CREATE INDEX "DEV"."I_FOODID$RECIPE" ON "DEV"."RECIPE" ("FOOD_ID");
   CREATE INDEX "DEV"."I_MEALID$RECIPE" ON "DEV"."RECIPE" ("MEAL_ID");
  
   COMMENT ON COLUMN "DEV"."RECIPE"."RCP_ID" IS 'Recipe identifier';
   COMMENT ON COLUMN "DEV"."RECIPE"."MEAL_ID" IS 'Meal identifier';
   COMMENT ON COLUMN "DEV"."RECIPE"."FOOD_ID" IS 'Food identifier';
   COMMENT ON COLUMN "DEV"."RECIPE"."AMOUNT" IS 'Food amount';
   COMMENT ON COLUMN "DEV"."RECIPE"."UNIT_ID" IS 'Unit identifier';
   COMMENT ON COLUMN "DEV"."RECIPE"."BEG_DATE" IS 'Start date';
   COMMENT ON COLUMN "DEV"."RECIPE"."END_DATE" IS 'End date';
