CREATE TABLE "DEV"."SERVING_SIZE"
   ("SZ_ID" NUMBER,
	"SRVNG_SIZE" VARCHAR2(100) NOT NULL ENABLE,
	"SRVNG_FACTOR" NUMBER,
	"SRVNG_CODE" VARCHAR2(100),
	 PRIMARY KEY ("SZ_ID")
      USING INDEX  ENABLE,
	 CONSTRAINT "UNIQUE_SRVNG_SIZE" UNIQUE ("SRVNG_SIZE")
      USING INDEX  ENABLE
   );
  
   CREATE UNIQUE INDEX "DEV"."UNIQUE_SRVNG_SIZE" ON "DEV"."SERVING_SIZE" ("SRVNG_SIZE");

   COMMENT ON COLUMN "DEV"."SERVING_SIZE"."SZ_ID" IS 'Serving size identifier';
   COMMENT ON COLUMN "DEV"."SERVING_SIZE"."SRVNG_SIZE" IS 'Serving size title';
   COMMENT ON COLUMN "DEV"."SERVING_SIZE"."SRVNG_FACTOR" IS 'Serving size factor';
   COMMENT ON COLUMN "DEV"."SERVING_SIZE"."SRVNG_CODE" IS 'Serving size code';
